[[plugins]]
repo = 'yuezk/vim-js'
on_ft = ['javascript', 'javascript.jsx','typescript', 'typescript.tsx','typescriptreact']


[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'javascript.jsx','typescript', 'typescript.tsx','typescriptreact']


[[plugins]]
repo='leafgarland/typescript-vim'
on_ft = ['javascript', 'javascript.jsx','typescript', 'typescript.tsx','typescriptreact']


[[plugins]]
repo='skanehira/preview-markdown.vim'
on_ft='md'
hook_add='''
let g:preview_markdown_parser='glow'
let g:preview_markdown_vertical=1
'''
